[package]
edition = "2021"
name = "endec"
version = "1.0.0"
license = "GPL-3.0"

[lib]
doctest = false

[dependencies]
chacha20poly1305 = { version = "0.10.1", default-features = false, features = [
    "heapless",
] }
