[package]
edition = "2021"
name = "etpwtc"
version = "1.0.0"
license = "GPL-3.0"

[lib]
proc-macro = true

[dependencies]
endec = { path = "../endec" }
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
